// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Address: typeof import('./components/System/Address.vue')['default']
    AddressDesigned: typeof import('./components/System/AddressDesigned.vue')['default']
    Collapse: typeof import('./components/System/Collapse.vue')['default']
    Footer: typeof import('./components/App/Footer/Footer.vue')['default']
    HashInput: typeof import('./components/System/HashInput.vue')['default']
    Header: typeof import('./components/App/Header/Header.vue')['default']
    Information: typeof import('./components/System/Information.vue')['default']
    JazzIcon: typeof import('./components/System/JazzIcon.vue')['default']
    JazzIconWrapper: typeof import('./components/System/JazzIconWrapper.vue')['default']
    L2toL1message: typeof import('./components/App/Receipt/L2toL1message.vue')['default']
    LinkToEtherscan: typeof import('./components/System/LinkToEtherscan.vue')['default']
    LinkToVoyager: typeof import('./components/System/LinkToVoyager.vue')['default']
    Logo: typeof import('./components/System/Logo.vue')['default']
    Page: typeof import('./components/App/Layout/Page.vue')['default']
    PageContent: typeof import('./components/App/Layout/PageContent.vue')['default']
    Pulse: typeof import('./components/System/Pulse.vue')['default']
    README: typeof import('./components/README.md')['default']
    Receipt: typeof import('./components/Receipt/Receipt.vue')['default']
    ReceiptParsed: typeof import('./components/Receipt/ReceiptParsed.vue')['default']
    ReceiptParsedError: typeof import('./components/Receipt/ReceiptParsedError.vue')['default']
    ReceiptParsedEvents: typeof import('./components/Receipt/ReceiptParsedEvents.vue')['default']
    ReceiptParsedMessages: typeof import('./components/Receipt/ReceiptParsedMessages.vue')['default']
    ReceiptParsedResources: typeof import('./components/Receipt/ReceiptParsedResources.vue')['default']
    StarknetLogo: typeof import('./components/Logos/StarknetLogo.vue')['default']
    'Uil:github': typeof import('~icons/uil/github')['default']
    'Uil:twitter': typeof import('~icons/uil/twitter')['default']
  }
}

export { }
