// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/App/Footer/Footer.vue')['default']
    Header: typeof import('./components/App/Header/Header.vue')['default']
    'Ic:baselineOpenInNew': typeof import('~icons/ic/baseline-open-in-new')['default']
    Logo: typeof import('./components/System/Logo.vue')['default']
    Page: typeof import('./components/App/Layout/Page.vue')['default']
    PageContent: typeof import('./components/App/Layout/PageContent.vue')['default']
    README: typeof import('./components/README.md')['default']
    Receipt: typeof import('./components/Receipt/Receipt.vue')['default']
    'Uil:twitter': typeof import('~icons/uil/twitter')['default']
  }
}

export { }
